package neo.landscape.theory.apps.pseudoboolean.problems;

import java.io.PrintWriter;
import java.io.Writer;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import java.util.stream.IntStream;

public class NKAlphaGenerator {


    // Helper to pick weighted index i given current outDegree[] and excluding those in excluded set
    // Returns -1 if no eligible candidate
    private static int weightedPick(int[] outDeg, Set<Integer> excluded, double alpha, Random rng) {
        double total = 0.0;
        int N = outDeg.length;
        double[] weights = new double[N];
        for (int i = 0; i < N; i++) {
            if (excluded.contains(i)) {
                weights[i] = 0.0;
            } else if (outDeg[i] >= N) {
                weights[i] = 0.0;
            } else {
                // weight = (outDegree[i])^alpha
                weights[i] = Math.pow(outDeg[i], alpha);
                total += weights[i];
            }
        }
        if (total <= 0.0) return -1;
        double r = rng.nextDouble() * total;
        double cum = 0.0;
        for (int i = 0; i < N; i++) {
            cum += weights[i];
            if (r <= cum) return i;
        }
        // fallback
        for (int i = N - 1; i >= 0; i--) if (weights[i] > 0) return i;
        return -1;
    }

    // Fisher-Yates shuffle
    private static void shuffleArray(int[] array, Random rng) {
        for (int i = array.length - 1; i > 0; i--) {
            int j = rng.nextInt(i + 1);
            int tmp = array[i];
            array[i] = array[j];
            array[j] = tmp;
        }
    }

    /**
     * NK-alpha model implementation.
     *
     * N: number of loci
     * K: each locus has K other inputs + itself = K+1 in-degree
     * alpha: exponent for preferential attachment (>= 0). alpha == 0 => uniform random.
     *
     * Notes:
     * - inputs[j] is an int[] of the indices (length <= K+1, ideally K+1) that determine locus j's contribution.
     * - outDegree[i] counts how many outgoing edges node i currently has (starts at 1 for the self-edge).
     */
    public static void generateNKAlpha(int N, int K, int Q, double alpha, long seed, Writer wr) {
        if (N <= 0) throw new IllegalArgumentException("N must be > 0");
        if (K < 0 || K > N-1) throw new IllegalArgumentException("K must be in 0 <= K <= N-1");
        if (alpha < 0) throw new IllegalArgumentException("alpha must be >= 0");
        Random rng = new Random(seed);

        int [] outDegree = new int[N];
        // temporary structure while building: use HashSet for fast contains check
        @SuppressWarnings("unchecked")
        HashSet<Integer>[] tmpInputs = new HashSet[N];
        for (int i = 0; i < N; i++) {
            tmpInputs[i] = new HashSet<>();
            tmpInputs[i].add(i); // each locus has a self-connection initially
            outDegree[i] = 1;
        }

        // Build the edges: K passes, each pass visits loci in random order
        for (int pass = 0; pass < K; pass++) {
            int[] order = IntStream.range(0, N).toArray();
            shuffleArray(order, rng);

            for (int j : order) {
                // If j already has N distinct inputs, can't add any more distinct incoming edges
                if (tmpInputs[j].size() >= N) continue;  // FIXME: this cannot happen
                // choose source i with probability proportional to (outDegree[i])^alpha,
                // but excluding i that already are in tmpInputs[j] or whose outDegree == N
                int chosen = weightedPick(outDegree, tmpInputs[j], alpha, rng);
                if (chosen >= 0) {
                    tmpInputs[j].add(chosen);
                    outDegree[chosen] = Math.min(N, outDegree[chosen] + 1); // FIXME: it cnnot rech N
                } else {
                    // no eligible candidate (rare). skip.
                }
            }
        }

        PrintWriter pw = new PrintWriter(wr);

        pw.println("c NKAlpha-landscape instance");
        pw.println("c Generated by " + NKAlphaGenerator.class.getName());
        pw.println("c The next line contains N and K");
        pw.println("p NK " + N + " " + K);
        pw.println("c For each subfunction first it appears the mask in a line starting with 'm'");
        pw.println("c The mask is a list of K+1 values with the indices of the variables in Big Endian order");
        pw.println("c Following the mask the subfunction is defined in a line without prefix");
        pw.println("c Random seed: " + seed);

        // Convert tmpInputs to int[] and enforce ordering (optional: deterministic order)
        for (int i = 0; i < N; i++) {
            // Write the mask
            pw.print("m ");
            for (int j: tmpInputs[i] ) {
                pw.print(j + " ");
            }
            pw.println();
            // Write the subfunction values
            for (int j = 0; j < 1 << (K+1); j++) {
                pw.print(rng.nextInt(Q) + " ");
            }
            pw.println();
        }
        pw.flush();

    }

    public static void main (String args[]) throws Exception {
        if (args.length != 5) {
            System.err.println("Usage: java NKAlphaGenerator <N> <K> <Q> <alpha> <seed>");
            System.exit(1);
        }
        int N = Integer.parseInt(args[0]);
        int K = Integer.parseInt(args[1]);
        int Q = Integer.parseInt(args[2]);
        double alpha = Double.parseDouble(args[3]);
        long seed = Long.parseLong(args[4]);

        generateNKAlpha(N, K, Q, alpha, seed, new PrintWriter(System.out));
    }
}
